# This is yaml for h3c router xpath info

tplink:
  passwd: 12345678
  password_element:
    ax6000: lgPwd
    wr842: pcPassword
  signin_element:
    ax6000: //*[@id="Login"]/div[2]/ul/li[4]
    wr842: loginBtn
  signin_done_element: tpLogo

  wireless_mode_select_element:
   ax6000:
      mode_2g: //*[@id="wlanMode"]/i
      mode_5g: //*[@id="wlanMode5g"]/i


  wireless_mode_element:
    ax6000:
      mode_2g: //*[@id="selOptsUlwlanMode"]/li[{}]
      mode_5g: //*[@id="selOptsUlwlanMode5g"]/li[{}]
    wr842: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[2]/tbody/tr[1]/td/table/tbody/tr[4]/td[2]/select/option[{}]

  ssid_element_2g:
    ax6000: ssid
    wr842: body > center > form > table > tbody > tr:nth-child(2) > td > table > tbody > tr:nth-child(1) > td:nth-child(2) > table:nth-child(2) > tbody > tr:nth-child(1) > td > table > tbody > tr:nth-child(1) > td:nth-child(2) > input
  ssid_element_5g: ssid5g

  #  //*[@id="WLgeneral"]/tbody/tr[11]/td/select/option[4]
  channel_select_element:
    ax6000:
      channel_2g: //*[@id="channel"]/i
      channel_5g: //*[@id="channel5g"]/i
    wr842: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[2]/tbody/tr[1]/td/table/tbody/tr[3]/td[2]/select/option[{}]

  channel_regu_element:
    channel_2g: //*[@id="selOptsUlchannel"]/li[{}]
    channel_5g: //*[@id="selOptsUlchannel5g"]/li[{}]

  bandwidth_select_element:
    bandwidth_2g: //*[@id="wlanWidth"]/i
    bandwidth_5g: //*[@id="wlanWidth5g"]/i
  bandwidth_element:
    ax6000:
      bandwidth_2g: //*[@id="selOptsUlwlanWidth"]/li[{}]
      bandwidth_5g: //*[@id="selOptsUlwlanWidth5g"]/li[{}]
    wr842: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[2]/tbody/tr[1]/td/table/tbody/tr[5]/td[2]/select/option[{}]

  authentication_select_element:
    authtication_2g: //*[@id="auth2gDiv"]/ul[1]/li
    authtication_5g: //*[@id="auth5gDiv"]/ul[1]/li
  authentication_regu_element:
    authtication_2g: //*[@id="selOptsUlauth"]/li[{}]
    authtication_5g: //*[@id="selOptsUlauth5g"]/li[{}]

  wr842_authentication_element:
    WPA-PSK/WPA2-PSK: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[4]/tbody/tr[1]/td/input
    WPA/WPA2: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[6]/tbody/tr[1]/td/input
    WEP: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[8]/tbody/tr[1]/td/input
    NONE: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[3]/tbody/tr/td/input

  wr842_authentication_select_element:
    WPA-PSK/WPA2-PSK: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[4]/tbody/tr[2]/td[2]/select/option[{}]
    WPA/WPA2: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[6]/tbody/tr[2]/td[2]/select/option[{}]
    WEP: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[8]/tbody/tr[2]/td[2]/select/option[{}]

  wr842_authentication_encrypt_element:
    WPA-PSK/WPA2-PSK: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[4]/tbody/tr[3]/td[2]/select/option[{}]
    WPA/WPA2: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[6]/tbody/tr[3]/td[2]/select/option[{}]
    WEP: /html/body/center/form/table/tbody/tr[2]/td/table/tbody/tr[1]/td[2]/table[8]/tbody/tr[3]/td[2]/select/option[{}]

  wr842_passwd_element:
    WPA-PSK/WPA2-PSK: pskSecret
    WPA/WPA2: radiusSecret
    WEP: key1
  passwd_element: wpa_key
  wep_encrypt_regu_element: //*[@id="WLgeneral"]/tbody/tr[16]/td/select/option[{}]
  wpa_encrypt_regu_element: //*[@id="WLgeneral"]/tbody/tr[14]/td/select/option[{}]
  passwd_index_regu_element: //*[@id="WLgeneral"]/tbody/tr[17]/td/select/option[{}]

  wep_passwd_element: wpa_key

  wpa_passwd:
    passwd_2g: wlanPwd
    passwd_5g: wlanPwd5g

  protect_frame_regu_element: //*[@id="WLgeneral"]/tbody/tr[26]/td/select/option[{}]

  apply_element:
    ax6000:
      apply_2g: save
      apply_5g: save5g
    wr842: Save
  setting_load_element: //*[@id="loadingBlock"]/tbody/tr/td[2]

  wait_reboot_element:
    asus_86u: /html/body/form/div/div/div[1]/div[2]
    asus_88u: /html/body/form/div/div/div[2]

