# This is yaml for xiaomi router xpath info

xiaomi:
  address:
#    ax3000: http://192.168.31.1/cgi-bin/luci/web
#    ax3000: http://192.168.5.1/cgi-bin/luci/web
    ax3000: http://192.168.1.1/
  passwd: 12345678
  password_element: password
  signin_element: btnRtSubmit
  signin_done_element: logo

  #  band_element: //*[@id="wl_unit_field"]/td/select
  wireless_mode_element: //*[@id="wlanMode"]
  ssid_element:
    ssid_2g: //*[@id="wifiset24"]/div[2]/span/input
    ssid_5g: //*[@id="wifiset50"]/div[2]/span/input

  #  //*[@id="WLgeneral"]/tbody/tr[11]/td/select/option[4]
  channel_regu_element: //*[@id="dummydata"]/a[{}]/span
  channel_select_element:
    channel_2g: //*[@id="wifiset24"]/div[6]/span/div
    channel_5g: //*[@id="wifiset50"]/div[6]/span/div
  bandwidth_element: //*[@id="dummydata"]/a[{}]/span
  bandwidth_select_element:
    bandwidth_2g: //*[@id="wifiset24"]/div[7]/span/div
    bandwidth_5g: //*[@id="wifiset50"]/div[7]/span/div
  authentication_regu_element: //*[@id="dummydata"]/a[{}]/span
  authentication_select_element:
    authentication_2g: //*[@id="wifiset24"]/div[4]/span/div
    authentication_5g: //*[@id="wifiset50"]/div[4]/span/div

  passwd_element:
    passwd_2g: //*[@id="wifiset24"]/div[5]/span/input
    passwd_5g: //*[@id="wifiset50"]/div[5]/span/input

  hide_ssid:
    hide_2g: hidessid0
    hide_5g: hidessid1
  apply_element:
    'apply_2g': //*[@id="wifiset24"]/div[9]/button/span
    'apply_5g': //*[@id="wifiset50"]/div[9]/button/span


