dict_Sheet1 = {'': ''}


dict_log_type = {'log type(7bit)': 'Message', 
'0x00': 'pure_data', 
'0x01': 'HCI_Command', 
'0x02': 'HCI_Event', 
'0x03': 'LMP_PDU', 
'0x04': 'LE_LL_Control_PDU', 
'0x05': 'Interrupt_type', 
'0x06': 'Inquiry_fsm', 
'0x07': 'Inquiry_scan_fsm', 
'0x08': 'Page_fsm', 
'0x09': 'Page_scan_fsm', 
'0x0a': 'LE_fsm', 
'0x0b': 'LE_adv_sub_fsm', 
'0x0c': 'LE_scan_sub_fsm', 
'0x0d': 'LE_connection_sub_fsm', 
'0x0e': 'LE_adv_pdu', 
'0x0f': 'Sleep_sub_fsm', 
'0x10': 'Packet_type', 
'0x11': 'TXRXstatus', 
'0x12': 'error_code_msg', 
'0x13': 'ack_nak', 
'0x14': 'queue_full', 
'0x15': 'trig_msg', 
'0x16': 'seqn_msg', 
'0x17': 'LE_ce_msg', 
'0x18': 'bt_clock_msg', 
'0x19': 'debug_log_msg', 
'0x1a': 'version_msg', 
'0x1b': 'le_tx_rx_len', 
'0x1c': 'acl_data', 
'0x1d': 'sco_data', 
'0x1e': 'enc_dec_counter', 
'0x1f': 'classic_le_switch', 
'0x20': 'bt_wifi_coex', 
'0x21': 'link_id', 
'0x22': 'role_log', 
'0x23': 'pc_debug_log_msg', 
'0x24': 'sjr_debug_log_msg', 
'0x25': 'xyz_debug_log_msg', 
'0x26': 'bei_debug_log_msg', 
'0x28': 'init_debug_log_msg',
'0x29': 'jkm_debug_log_msg',
'0x30': 'isoal_debug_log_msg', 
'0x31': 'big_debug_log_msg', 
'0x32': 'cig_debug_log_msg', 
'0x33': 'le_audio_debug_log_msg', 
'0x34': 'pawr_debug_log_msg', 
'0x35': 'le_conn_debug_log_msg', 
'0x36': 'le_adv_debug_log_msg', 
'0x37': 'le_scan_debug_log_msg', 
'0x38': 'le_ll_debug_log_msg', 
'0x39': 'le_comm_debug_log_msg', 
'0x40': 'event_list_debug_log_msg', 
'0x41': 'host_if_debug_log_msg', 
'0x50': '15p4_general_log', 
'0x51': '15p4_performance_log', 
'0x52': '15p4_lp_log', 
'0x53': '15p4_info_log', 
'0x54': '15p4_int_log', 
'0x55': '15p4_key_log', 
'0x56': '15p4_error_log',
'0x70': 'DBG_COEX_ARB_LOG',
'0x71': 'DBG_COEX_BT_LOG',
'0x72': 'DBG_COEX_15P4_LOG',
'0x73': 'DBG_COEX_WIFI_LOG',
'0x7f': 'verify_type'}


dict_HCI_Event = {'HCI Event': '', 'Event_code': 'Event_body', '0x01': 'HCI_INQUIRY_COMPLETE_EVENT', '0x02': 'HCI_INQUIRY_RESULT_EVENT', '0x03': 'HCI_CONNECTION_COMPLETE_EVENT', '0x04': 'HCI_CONNECTION_REQUEST_EVENT', '0x05': 'HCI_DISCONNECTION_COMPLETE_EVENT', '0x06': 'HCI_AUTHENTICATION_COMPLETE_EVENT', '0x07': 'HCI_READ_REMOTE_NAME_REQUEST_COMPLETE_EVENT', '0x08': 'HCI_ENCRYPTION_CHANGE_EVENT', '0x09': 'HCI_CHANGE_CONNECTION_LINK_KEY_COMPLETE_EVENT', '0x0a': 'HCI_MASTER_LINK_KEY_COMPLETE_EVENT', '0x0b': 'HCI_READ_REMOTE_SUPPORTED_FEATURES_COMPLETE_EVENT', '0x0c': 'HCI_READ_REMOTE_VERSION_INFORMATION_COMPLETE_EVENT', '0x0d': 'HCI_QoS_SETUP_COMPLETE_EVENT', '0x0e': 'HCI_COMMAND_COMPLETE_EVENT', '0x0f': 'HCI_COMMAND_STATUS_EVENT', '0x10': 'HCI_HARDWARE_ERROR_EVENT', '0x11': 'HCI_FLUSH_OCCURED_EVENT', '0x12': 'HCI_ROLE_CHANGE_EVENT', '0x13': 'HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT', '0x14': 'HCI_MODE_CHANGE_EVENT', '0x15': 'HCI_RETURN_LINK_KEYS_EVENT', '0x16': 'HCI_PIN_CODE_REQUEST_EVENT', '0x17': 'HCI_LINK_KEY_REQUEST_EVENT', '0x18': 'HCI_LINK_KEY_NOTIFICATION_EVENT', '0x19': 'HCI_LOOPBACK_COMMAND_EVENT', '0x1a': 'HCI_DATA_BUFFER_OVERFLOW_EVENT', '0x1b': 'HCI_MAX_SLOTS_CHANGE_EVENT', '0x1c': 'HCI_READ_CLOCK_OFFSET_EVENT', '0x1d': 'HCI_CONNECTION_PACKET_TYPE_CHANGED_EVENT', '0x1e': 'HCI_QOS_VIOLATION_EVENT', '0x1f': 'HCI_PAGE_SCAN_MODE_CHANGE_EVENT', '0x20': 'HCI_PAGE_SCAN_REPETITION_MODE_CHANGE_EVENT', '0x21': 'HCI_FLOW_SPECIFICATION_COMPLETE_EVENT', '0x22': 'HCI_INQUIRY_RESULT_EVENT_WITH_RSSI', '0x23': 'HCI_READ_REMOTE_EXTENDED_FEATURES_COMPLETE_EVENT', '0x24': 'HCI_DEBUG_EVENT', '0x25': 'HCI_ALIAS_ADDRESS_EVENT', '0x27': 'HCI_ACTIVE_ADDRESS_EVENT', '0x2c': 'HCI_SYNCHRONOUS_CONNECTION_COMPLETE_EVENT', '0x2d': 'HCI_SYNCHRONOUS_CONNECTION_CHANGED_EVENT', '0x2e': 'HCI_SNIFF_SUBRATING_EVENT', '0x2f': 'HCI_EXTENDED_INQUIRY_RESULT_EVENT', '0x30': 'HCI_ENCRYPTION_KEY_REFRESH_COMPLETE_EVENT', '0x31': 'HCI_IO_CAPABILITY_REQUEST_EVENT', '0x32': 'HCI_IO_CAPABILITY_RESPONSE_EVENT', '0x33': 'HCI_USER_CONFIRMATION_REQUEST_EVENT', '0x34': 'HCI_USER_PASSKEY_REQUEST_EVENT', '0x35': 'HCI_REMOTE_OOB_DATA_REQUEST_EVENT', '0x36': 'HCI_SIMPLE_PAIRING_COMPLETE_EVENT', '0x38': 'HCI_LINK_SUPERVISION_TIMEOUT_CHANGED_EVENT', '0x39': 'HCI_ENHANCED_FLUSH_COMPLETE_EVENT', '0x3b': 'HCI_USER_PASSKEY_NOTIFICATION_EVENT', '0x3c': 'HCI_KEYPRESS_NOTIFICATION_EVENT', '0x3d': 'HCI_REMOTE_HOST_SUPPORTED_FEATURES_NOTIFICATION_EVENT', '0x3e': 'HCI_LE_EVENT', '0x57': 'HCI_AUTHENTICATION_PAYLOAD_TIMEOUT_EXCEEDED', '0x58': 'HCI_SAM_STATUS_CHANGE_EVENT', '0x59': 'HCI_ENCRYPTION_CHANGE_EVENT_V2'}


dict_HCI_Command = {'HCI Command': '', 'Opcode': 'Command', '0x0401': 'HCI_INQUIRY', '0x0402': 'HCI_INQUIRY_CANCEL', '0x0403': 'HCI_PERIODIC_INQUIRY_MODE', '0x0404': 'HCI_EXIT_PERIODIC_INQUIRY_MODE', '0x0405': 'HCI_CREATE_CONNECTION', '0x0406': 'HCI_DISCONNECT', '0x0407': 'HCI_ADD_SCO_CONNECTION', '0x0408': 'HCI_CREATE_CONNECTION_CANCEL', '0x0409': 'HCI_ACCEPT_CONNECTION_REQUEST', '0x040a': 'HCI_REJECT_CONNECTION_REQUEST', '0x040b': 'HCI_LINK_KEY_REQUEST_REPLY', '0x040c': 'HCI_LINK_KEY_REQUEST_NEGATIVE_REPLY', '0x040d': 'HCI_PIN_CODE_REQUEST_REPLY', '0x040e': 'HCI_PIN_CODE_REQUEST_NEGATIVE_REPLY', '0x040f': 'HCI_CHANGE_CONNECTION_PACKET_TYPE', '0x0411': 'HCI_AUTHENTICATION_REQUESTED', '0x0413': 'HCI_SET_CONNECTION_ENCRYPTION_ENABLE', '0x0415': 'HCI_CHANGE_CONNECTION_LINK_KEY', '0x0417': 'HCI_MASTER_LINK_KEY', '0x0419': 'HCI_REMOTE_NAME_REQUEST', '0x041a': 'HCI_REMOTE_NAME_REQUEST_CANCEL', '0x041b': 'HCI_READ_REMOTE_FEATURES', '0x041c': 'HCI_READ_REMOTE_EXTENDED_FEATURES', '0x041d': 'HCI_READ_REMOTE_VER_INFO', '0x041f': 'HCI_READ_CLOCK_OFFSET', '0x0420': 'HCI_READ_LMP_HANDLE', '0x0421': 'HCI_EXCHANGE_FIXED_INFO', '0x0422': 'HCI_EXCHANGE_ALIAS_INFO', '0x0423': 'HCI_PRIVATE_PAIRING_REQUEST_REPLY', '0x0424': 'HCI_PRIVATE_PAIRING_REQUEST_NEGATIVE_REPLY', '0x0425': 'HCI_GENERATED_ALIAS', '0x0426': 'HCI_ALIAS_ADDRESS_REQUEST_REPLY', '0x0427': 'HCI_ALIAS_ADDRESS_REQUEST_NEGATIVE_REPLY', '0x0428': 'HCI_SETUP_SYNCHRONOUS_CONNECTION', '0x0429': 'HCI_ACCEPT_SYNCHRONOUS_CONNECTION_REQUEST', '0x042a': 'HCI_REJECT_SYNCHRONOUS_CONNECTION_REQUEST', '0x042b': 'HCI_IO_CAPABILITY_REQUEST_REPLY', '0x042c': 'HCI_USER_CONFIRMATION_REQUEST_REPLY', '0x042d': 'HCI_USER_CONFIRMATION_REQUEST_NEGATIVE_REPLY', '0x042e': 'HCI_USER_PASSKEY_REQUEST_REPLY', '0x042f': 'HCI_USER_PASSKEY_REQUEST_NEGATIVE_REPLY', '0x0430': 'HCI_REMOTE_OOB_DATA_REQUEST_REPLY', '0x0433': 'HCI_REMOTE_OOB_DATA_REQUEST_NEGATIVE_REPLY', '0x0434': 'HCI_IO_CAPABILITY_REQUEST_NEGATIVE_REPLY', '': '', '0x0801': 'HCI_HOLD_MODE', '0x0803': 'HCI_SNIFF_MODE', '0x0804': 'HCI_EXIT_SNIFF_MODE', '0x0805': 'HCI_PARK_MODE', '0x0806': 'HCI_EXIT_PARK_MODE', '0x0807': 'HCI_QOS_SETUP', '0x0809': 'HCI_ROLE_DISCOVERY', '0x080b': 'HCI_SWITCH_ROLE', '0x080c': 'HCI_READ_LINK_POLICY_SETTINGS', '0x080d': 'HCI_WRITE_LINK_POLICY_SETTINGS', '0x080e': 'HCI_READ_DEFAULT_LINK_POLICY_SETTINGS', '0x080f': 'HCI_WRITE_DEFAULT_LINK_POLICY_SETTINGS', '0x0810': 'HCI_FLOW_SPECIFICATION', '0x0811': 'HCI_SNIFF_SUBRATING', '0x0c01': 'HCI_SET_EVENT_MASK', '0x0c03': 'HCI_RESET', '0x0c05': 'HCI_SET_EVENT_FILTER', '0x0c08': 'HCI_FLUSH', '0x0c09': 'HCI_READ_PIN_TYPE', '0x0c0a': 'HCI_WRITE_PIN_TYPE', '0x0c0b': 'HCI_CREATE_NEW_UNIT_KEY', '0x0c0d': 'HCI_READ_STORED_LINK_KEY', '0x0c11': 'HCI_WRITE_STORED_LINK_KEY', '0x0c12': 'HCI_DELETE_STORED_LINK_KEY', '0x0c13': 'HCI_CHANGE_LOCAL_NAME', '0x0c14': 'HCI_READ_LOCAL_NAME', '0x0c15': 'HCI_READ_CONNECT_ACCEPT_TO', '0x0c16': 'HCI_WRITE_CONNECT_ACCEPT_TO', '0x0c17': 'HCI_READ_PAGE_TIMEOUT', '0x0c18': 'HCI_WRITE_PAGE_TIMEOUT', '0x0c19': 'HCI_READ_SCAN_ENABLE', '0x0c1a': 'HCI_WRITE_SCAN_ENABLE', '0x0c1b': 'HCI_READ_PAGE_SCAN_ACT', '0x0c1c': 'HCI_WRITE_PAGE_SCAN_ACT', '0x0c1d': 'HCI_READ_INQUIRY_SCAN_ACT', '0x0c1e': 'HCI_WRITE_INQUIRY_SCAN_ACT', '0x0c1f': 'HCI_READ_AUTHENTICATION_ENABLE', '0x0c20': 'HCI_WRITE_AUTHENTICATION_ENABLE', '0x0c21': 'HCI_READ_ENCRYPTION_MODE', '0x0c22': 'HCI_WRITE_ENCRYPTION_MODE', '0x0c23': 'HCI_READ_CLASS_OF_DEVICE', '0x0c24': 'HCI_WRITE_CLASS_OF_DEVICE', '0x0c25': 'HCI_READ_VOICE_SETTINGS', '0x0c26': 'HCI_WRITE_VOICE_SETTINGS', '0x0c27': 'HCI_READ_AUTOMATIC_FLUSH_TIMEOUT', '0x0c28': 'HCI_WRITE_AUTOMATIC_FLUSH_TIMEOUT', '0x0c29': 'HCI_READ_NUM_BROADCAST_RETRANSMISSIONS', '0x0c2a': 'HCI_WRITE_NUM_BROADCAST_RETRANSMISSIONS', '0x0c2b': 'HCI_READ_HOLD_MODE_ACTIVITY', '0x0c2c': 'HCI_WRITE_HOLD_MODE_ACTIVITY', '0x0c2d': 'HCI_READ_TRANSMIT_POWER_LEVEL', '0x0c2e': 'HCI_READ_SYNCHRONOUS_FLOW_CONTROL_ENABLE', '0x0c2f': 'HCI_WRITE_SYNCHRONOUS_FLOW_CONTROL_ENABLE', '0x0c31': 'HCI_SET_HOST_CONTROLLER_TO_HOST_FLOW_CONTROL', '0x0c33': 'HCI_HOST_BUFFER_SIZE', '0x0c35': 'HCI_HOST_NUMBER_OF_COMPLETED_PACKETS', '0x0c36': 'HCI_READ_SUPERVISION_TIMEOUT', '0x0c37': 'HCI_WRITE_SUPERVISION_TIMEOUT', '0x0c38': 'HCI_READ_NUMBER_OF_SUPPORTED_IAC', '0x0c39': 'HCI_READ_CURRENT_IAC_LAP', '0x0c3a': 'HCI_WRITE_CURRENT_IAC_LAP', '0x0c3b': 'HCI_READ_PAGE_SCAN_PERIOD_MODE', '0x0c3c': 'HCI_WRITE_PAGE_SCAN_PERIOD_MODE', '0x0c3d': 'HCI_READ_PAGE_SCAN_MODE', '0x0c3e': 'HCI_WRITE_PAGE_SCAN_MODE', '0x0c3f': 'HCI_SET_AFH_HOST_CHANNEL_CLASSIFICATION', '0x0c42': 'HCI_READ_INQUIRY_SCAN_TYPE', '0x0c43': 'HCI_WRITE_INQUIRY_SCAN_TYPE', '0x0c44': 'HCI_READ_INQUIRY_MODE', '0x0c45': 'HCI_WRITE_INQUIRY_MODE', '0x0c46': 'HCI_READ_PAGE_SCAN_TYPE', '0x0c47': 'HCI_WRITE_PAGE_SCAN_TYPE', '0x0c48': 'HCI_READ_AFH_CHANNEL_ASSESSMENT_MODE', '0x0c49': 'HCI_WRITE_AFH_CHANNEL_ASSESSMENT_MODE', '0x0c50': 'HCI_RESET_FIXED_ADDRESS_ATTEMPTS_COUNTER', '0x0c51': 'HCI_READ_EXTENDED_INQUIRY_RESPONSE_COMMAND', '0x0c52': 'HCI_WRITE_EXTENDED_INQUIRY_RESPONSE_COMMAND', '0x0c53': 'HCI_REFRESH_ENCRYPTION_KEY', '0x0c55': 'HCI_READ_SIMPLE_PAIRING_MODE', '0x0c56': 'HCI_WRITE_SIMPLE_PAIRING_MODE', '0x0c57': 'HCI_READ_LOCAL_OOB_DATA', '0x0c58': 'HCI_READ_INQUIRY_RESPONSE_TRANSMIT_POWER_LEVEL', '0x0c59': 'HCI_WRITE_INQUIRY_TRANSMIT_POWER_LEVEL', '0x0c5a': 'HCI_READ_DEFAULT_ERRONEOUS_DATA_REPORTING', '0x0c5b': 'HCI_WRITE_DEFAULT_ERRONEOUS_DATA_REPORTING', '0x0c5f': 'HCI_ENHANCED_FLUSH', '0x0c60': 'HCI_SEND_KEYPRESS_NOTIFICATION', '0x0c68': 'HCI_READ_ENHANCED_TRANSMIT_POWER_LEVEL', '0x0c6c': 'HCI_READ_LE_HOST_SUPPORT', '0x0c6d': 'HCI_WRITE_LE_HOST_SUPPORT', '0x0c7b': 'HCI_READ_AUTHENTICATED_PAYLOAD_TIMEOUT', '0x0c7c': 'HCI_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT', '0x0c79': 'HCI_READ_SECURE_CONNECTIONS_HOST_SUPPORT', '0x0c7a': 'HCI_WRITE_SECURE_CONNECTIONS_HOST_SUPPORT', '0x1001': 'HCI_READ_LOCAL_VER_INFO', '0x1002': 'HCI_READ_LOCAL_COMMANDS', '0x1003': 'HCI_READ_LOCAL_FEATURES', '0x1004': 'HCI_READ_LOCAL_EXTENDED_FEATURES', '0x1005': 'HCI_READ_BUFFER_SIZE', '0x1007': 'HCI_READ_COUNTRY_CODE', '0x1009': 'HCI_READ_BD_ADDR', '0x1401': 'HCI_READ_FAILED_CONTACT_COUNTER', '0x1402': 'HCI_RESET_FAILED_CONTACT_COUNTER', '0x1403': 'HCI_GET_LINK_QUALITY', '0x1405': 'HCI_READ_RSSI', '0x1406': 'HCI_READ_AFH_CHANNEL_MAP', '0x1407': 'HCI_READ_CLOCK', '0x1408': 'HCI_READ_ENCRYPTION_KEY_SIZE', '0x1801': 'HCI_READ_LOOPBACK_MODE', '0x1802': 'HCI_WRITE_LOOPBACK_MODE', '0x1803': 'HCI_ENABLE_DEVICE_UNDER_TEST_MODE', '0x1804': 'HCI_WRITE_SIMPLE_PAIRING_DEBUG_MODE', '0x2001': 'HCI_LE_SET_EVENT_MASK', '0x2002': 'HCI_LE_READ_BUFFER_SIZE', '0x2003': 'HCI_LE_READ_LOCAL_SUPPORTED_FEATURES', '0x2005': 'HCI_LE_SET_RANDOM_ADDRESS', '0x2006': 'HCI_LE_SET_ADVERTISING_PARAMETERS', '0x2007': 'HCI_LE_READ_ADVERTISING_CHANNEL_TX_POWER', '0x2008': 'HCI_LE_SET_ADVERTISING_DATA', '0x2009': 'HCI_LE_SET_SCAN_RESPONSE_DATA', '0x200a': 'HCI_LE_SET_ADVERTISE_ENABLE', '0x200b': 'HCI_LE_SET_SCAN_PARAMETERS', '0x200c': 'HCI_LE_SET_SCAN_ENABLE', '0x200d': 'HCI_LE_CREATE_CONNECTION', '0x200e': 'HCI_LE_CREATE_CONNECTION_CANCEL', '0x200f': 'HCI_LE_READ_WHITE_LIST_SIZE', '0x2010': 'HCI_LE_CLEAR_WHITE_LIST', '0x2011': 'HCI_LE_ADD_DEVICE_TO_WHITE_LIST', '0x2012': 'HCI_LE_REMOVE_DEVICE_FROM_WHITE_LIST', '0x2013': 'HCI_LE_CONNECTION_UPDATE', '0x2014': 'HCI_LE_SET_HOST_CHANNEL_CLASSIFICATION', '0x2015': 'HCI_LE_READ_CHANNEL_MAP', '0x2016': 'HCI_LE_READ_REMOTE_USED_FEATURES', '0x2017': 'HCI_LE_ENCRYPT', '0x2018': 'HCI_LE_RAND', '0x2019': 'HCI_LE_START_ENCRYPTION', '0x201a': 'HCI_LE_LONG_TERM_KEY_REQUEST_REPLY', '0x201b': 'HCI_LE_LONG_TERM_KEY_REQUEST_NEGATIVE_REPLY', '0x201c': 'HCI_LE_READ_SUPPORTED_STATES', '0x201d': 'HCI_LE_RECEIVER_TEST', '0x201e': 'HCI_LE_TRANSMITTER_TEST', '0x201f': 'HCI_LE_TEST_END', '0x2020': 'HCI_LE_REMOTE_CONNECTION_PARAM_REQUEST_REPLY', '0x2021': 'HCI_LE_REMOTE_CONNECTION_PARAM_REQUEST_NEGATIVE_REPLY', '0x2027': 'HCI_LE_ADD_DEVICE_TO_RESOLVING_LIST', '0x202b': 'HCI_LE_READ_PEER_RESOLVABLE_ADDRESS', '0x202d': 'HCI_LE_SET_ADDRESS_RESOLUTION_ENABLE', '0x202e': 'HCI_LE_SET_RESOLVABLE_PRIVATE_ADDRESS_TIMEOUT', '0x2036': 'HCI_SET_EXTENDED_ADVERTISING_PARAMETERS', '0x2037': 'HCI_SET_EXTENDED_ADVERTISING_DATA', '0x2038': 'HCI_SET_EXTENDED_SCAN_RESPONSE_DATA', '0x2039': 'HCI_SET_EXTENDED_ADVERTISING_ENABLE', '0x203a': 'HCI_LE_READ_MAX_ADVERTISING_DATA_LENGTH', '0x203b': 'HCI_LE_READ_NUMBER_OF_SUPPORTED_ADVERTISING_SETS', '0x203c': 'HCI_LE_REMOVE_ADVERTISING_SET', '0x203d': 'HCI_LE_CLEAR_ADVERTISING_SETS', '0x203e': 'HCI_SET_PERIODIC_ADVERTISING_PARAM', '0x203f': 'HCI_SET_PERIODIC_ADVERTISING_DATA', '0x2040': 'HCI_SET_PERIODIC_ADVERTISING_ENABLE', '0x2041': 'HCI_LE_SET_EXTENDED_SCAN_PARAM', '0x2042': 'HCI_LE_SET_EXTENDED_SCAN_ENABLE', '0x2043': 'HCI_LE_EXTENDED_CREATE_CONNECTION', '0x2044': 'HCI_LE_PERIODIC_ADVERTISING_CREATE_SYNC', '0x2045': 'HCI_LE_PERIODIC_ADVERTISING_CREATE_SYNC_CANCEL', '0x2046': 'HCI_LE_PERIODIC_ADVERTISING_TERMINATE_SYNC', '0x2047': 'HCI_LE_ADD_DEVICE_TO_PERIODIC_ADVERTISER_LIST', '0x2048': 'HCI_LE_REMOVE_DEVICE_FROM_PERIODIC_ADVERTISER_LIST', '0x2049': 'HCI_LE_CLEAR_PERIODIC_ADVERTISER_LIST', '0x204a': 'HCI_LE_READ_PERIODIC_ADVERTISER_LIST_SIZE', '0x204e': 'HCI_LE_SET_PRIVACY_MODE', '0x2059': 'HCI_LE_SET_PERIODIC_ADVERTISING_RECEIVE_ENABLE', '0x205a': 'HCI_LE_PERIODIC_ADVERTISING_SYNC_TRANSFER', '0x205b': 'HCI_LE_PERIODIC_ADVERTISING_SET_INFO_TRANSFER', '0x205c': 'HCI_LE_SET_PERIODIC_ADVERTISING_SYNC_TRANSFER_PARAM', '0x205d': 'HCI_LE_SET_DEFAULT_PERIODIC_ADVERTISING_SYNC_TRANSFER_PARAM', '0x205f': 'HCI_LE_MODIFY_SLEEP_CLOCK_ACCURACY', '0x2061': 'HCI_LE_READ_ISO_TX_SYNC', '0x2062': 'HCI_LE_SET_CIG_PARAM', '0x2063': 'HCI_LE_SET_CIG_PARAM_TEST', '0x2064': 'HCI_LE_CREATE_CIS', '0x2065': 'HCI_LE_REMOVE_CIG', '0x2066': 'HCI_LE_ACCEPT_CIS_REQUEST', '0x2067': 'HCI_LE_REJECT_CIS_REQUEST', '0x2068': 'HCI_LE_CREATE_BIG', '0x2069': 'HCI_LE_CREATE_BIG_TEST', '0x206a': 'HCI_LE_TERMINATE_BIG', '0x206b': 'HCI_LE_BIG_CREAE_SYNC', '0x206c': 'HCI_LE_BIG_TERMINATE_SYNC', '0x206d': 'HCI_LE_REQUEST_PEER_SCA', '0x206e': 'HCI_LE_SETUP_ISO_DATA_PATH', '0x206f': 'HCI_LE_REMOVE_ISO_DATA_PATH', '0x2070': 'HCI_LE_ISO_TRANSMIT_TEST', '0x2071': 'HCI_LE_ISO_RECEIVER_TEST', '0x2072': 'HCI_LE_READ_TEST_COUNTERS', '0x2073': 'HCI_LE_ISO_TEST_END', '0x2074': 'HCI_LE_SET_HOST_FEATURE', '0x2075': 'HCI_LE_READ_ISO_LINK_QUALITY', '0x2076': 'HCI_LE_ENHANCED_READ_TRANSMIT_POWER_LEVEL', '0x2077': 'HCI_LE_READ_REMOTE_TRANSMIT_POWER_LEVEL', '0x2078': 'HCI_LE_SET_PATH_LOSS_REPORTING_PARAM', '0x2079': 'HCI_LE_SET_PATH_LOSS_REPORTING_ENABLE', '0x207a': 'HCI_LE_SET_TRANSMIT_POWER_REPORTING_ENABLE', '0x207c': 'HCI_LE_SET_DATA_RELATED_ADDRESS_CHANGES', '0x207d': 'HCI_LE_SET_DEAULT_SUBRATE', '0x207e': 'HCI_LE_SUBRATE_REQUEST', '0x207f': 'HCI_LE_SET_EXTENDED_ADV_PARAMS_V2', '0x2080': 'HCI_LE_Set_Decision_Data', '0x2081': 'HCI_LE_Set_Decision_Instruction', '0x2082': 'HCI_LE_SET_PERIODIC_ADV_SUBEVENT_DATA', '0x2083': 'HCI_LE_SET_PERIODIC_ADV_RESPONSE_DATA', '0x2084': 'HCI_LE_SET_PERIODIC_SYNC_SUBEVENT', '0x2085': 'HCI_LE_EXT_CREATE_CONNECTION_V2', '0x2086': 'HCI_LE_SET_PERIODIC_ADV_PARAMS_V2'}


dict_LMP_PDU = {'LMP_In': '', '0x00': 'NO_OPERATION                    ', '0x01': 'LMP_NAME_REQ                    ', '0x02': 'LMP_NAME_RES                    ', '0x03': 'LMP_ACCEPTED                    ', '0x04': 'LMP_NOT_ACCEPTED                ', '0x05': 'LMP_CLKOFFSET_REQ               ', '0x06': 'LMP_CLKOFFSET_RES               ', '0x07': 'LMP_DETACH                      ', '0x08': 'LMP_IN_RAND                     ', '0x09': 'LMP_COMB_KEY                    ', '0x0a': 'LMP_UNIT_KEY                    ', '0x0b': 'LMP_AU_RAND                     ', '0x0c': 'LMP_SRES                        ', '0x0d': 'LMP_TEMP_RAND                   ', '0x0e': 'LMP_TEMP_KEY                    ', '0x0f': 'LMP_ENCRYPTION_MODE_REQ         ', '0x10': 'LMP_ENCRYPTION_KEY_SIZE_REQ     ', '0x11': 'LMP_START_ENCRYPTION_REQ        ', '0x12': 'LMP_STOP_ENCRYPTION_REQ         ', '0x13': 'LMP_SWITCH_REQ                  ', '0x14': 'LMP_HOLD                        ', '0x15': 'LMP_HOLD_REQ                    ', '0x16': 'LMP_SNIFF                       ', '0x17': 'LMP_SNIFF_REQ                   ', '0x18': 'LMP_UNSNIFF_REQ                 ', '0x19': 'LMP_PARK_REQ                    ', '0x1b': 'LMP_SET_BROADCAST_SCAN_WINDOW   ', '0x1c': 'LMP_MODIFY_BEACON               ', '0x1d': 'LMP_UNPARK_BD_ADDR_REQ          ', '0x1e': 'LMP_UNPARK_PM_ADDR_REQ          ', '0x1f': 'LMP_INCR_POWER_REQ              ', '0x20': 'LMP_DECR_POWER_REQ              ', '0x21': 'LMP_MAX_POWER                   ', '0x22': 'LMP_MIN_POWER                   ', '0x23': 'LMP_AUTO_RATE                   ', '0x24': 'LMP_PREFERRED_RATE              ', '0x25': 'LMP_VERSION_REQ                 ', '0x26': 'LMP_VERSION_RES                 ', '0x27': 'LMP_FEATURES_REQ                ', '0x28': 'LMP_FEATURES_RES                ', '0x29': 'LMP_QUALITY_OF_SERVICE          ', '0x2a': 'LMP_QUALITY_OF_SERVICE_REQ      ', '0x2b': 'LMP_SCO_LINK_REQ                ', '0x2c': 'LMP_REMOVE_SCO_LINK_REQ         ', '0x2d': 'LMP_MAX_SLOT                    ', '': '', '0x2e': 'LMP_MAX_SLOT_REQ                ', '0x2f': 'LMP_TIMING_ACCURACY_REQ         ', '0x30': 'LMP_TIMING_ACCURACY_RES         ', '0x31': 'LMP_SETUP_COMPLETE              ', '0x32': 'LMP_USE_SEMI_PERMANENT_KEY      ', '0x33': 'LMP_HOST_CONNECTION_REQ         ', '0x34': 'LMP_SLOT_OFFSET                 ', '0x35': 'LMP_PAGE_MODE_REQ               ', '0x36': 'LMP_PAGE_SCAN_MODE_REQ          ', '0x37': 'LMP_SUPERVISION_TIMEOUT         ', '0x38': 'LMP_TEST_ACTIVATE               ', '0x39': 'LMP_TEST_CONTROL                ', '0x3a': 'LMP_ENCRYPTION_KEY_SIZE_MASK_REQ', '0x3b': 'LMP_ENCRYPTION_KEY_SIZE_MASK_RES', '0x3c': 'LMP_SET_AFH                     ', '0x3d': 'LMP_ENCAPSULATED_HEADER         ', '0x3e': 'LMP_ENCAPSULATED_PAYLOAD        ', '0x3f': 'LMP_SIMPLE_PAIRING_CONFIRM      ', '0x40': 'LMP_SIMPLE_PAIRING_NUMBER       ', '0x41': 'LMP_DHKEY_CHECK                 ',  '0x42': 'LMP_pause_encryption_aes_req                 ', '0x7c': 'LMP_ESCAPE_1_OPCODE             ', '0x7d': 'LMP_ESCAPE_2_OPCODE             ', '0x7e': 'LMP_ESCAPE_3_OPCODE             ', '0x7f': 'LMP_ESCAPE_4_OPCODE             ', '0x81': 'LMP_ACCEPTED_EXT              ', '0x82': 'LMP_NOT_ACCEPTED_EXT          ', '0x83': 'LMP_FEATURES_REQ_EXT          ', '0x84': 'LMP_FEATURES_RES_EXT          ', '0x85': 'LMP_SCATTER_REQ               ', '0x86': 'LMP_UNSCATTER_REQ             ', '0x87': 'LMP_SET_SUBRATE               ', '0x88': 'LMP_SCATTER_ALGORITHMS_REQ    ', '0x89': 'LMP_SCATTER_ALGORITHMS_RES    ', '0x8a': 'LMP_PP_EXTENSION_REQ          ', '0x8b': 'LMP_PACKET_TYPE_TABLE_REQ     ', '0x8c': 'LMP_ESCO_LINK_REQ             ', '0x8f': 'LMP_REMOVE_ESCO_LINK_REQ      ', '0x90': 'LMP_CHANNEL_CLASSIFICATION_REQ', '0x91': 'LMP_CHANNEL_CLASSIFICATION    ', '0x92': 'LMP_ALIAS_ADDRESS             ', '0x93': 'LMP_ACTIVE_ADDRESS            ', '0x94': 'LMP_FIXED_ADDRESS             ', '0x95': 'LMP_SNIFF_SUBRATING_REQ       ', '0x96': 'LMP_SNIFF_SUBRATING_RES       ', '0x97': 'LMP_PAUSE_ENCRYPTION_REQ      ', '0x98': 'LMP_RESUME_ENCRYPTION_REQ     ', '0x99': 'LMP_IO_CAPABILITY_REQUEST     ', '0x9a': 'LMP_IO_CAPABILITY_RESPONSE    ', '0x9b': 'LMP_NUMERIC_COMPARISON_FAILED ', '0x9c': 'LMP_PASSKEY_ENTRY_FAILED      ', '0x9d': 'LMP_OOB_FAILED                ', '0x9e': 'LMP_KEYPRESS_NOTIFICATION     ', '0x9f': 'LMP_POWER_CONTROL_REQ         ', '0xa0': 'LMP_POWER_CONTROL_RESP     '}


dict_LE_LL_Control_PDU = {'LE_LL_Control_PDU_In': '', '0x00': 'LL_CONNECTION_UPDATE_IND', '0x01': 'LL_CHANNEL_MAP_IND', '0x02': 'LL_TERMINATE_IND', '0x03': 'LL_ENC_REQ', '0x04': 'LL_ENC_RSP', '0x05': 'LL_START_ENC_REQ', '0x06': 'LL_START_ENC_RSP', '0x07': 'LL_UNKNOWN_RSP', '0x08': 'LL_FEATURE_REQ', '0x09': 'LL_FEATURE_RSP', '0x0a': 'LL_PAUSE_ENC_REQ', '0x0b': 'LL_PAUSE_ENC_RSP', '0x0c': 'LL_VERSION_IND', '0x0d': 'LL_REJECT_IND', '0x0e': 'LL_SLAVE_FEATURE_REQ', '0x0f': 'LL_CONNECTION_PARAM_REQ', '0x10': 'LL_CONNECTION_PARAM_RSP', '0x11': 'LL_REJECT_EXT_IND', '0x12': 'LL_PING_REQ', '0x13': 'LL_PING_RSP', '0x14': 'LL_LENGTH_REQ', '0x15': 'LL_LENGTH_RSP', '0x16': 'LL_PHY_REQ', '0x17': 'LL_PHY_RSP', '0x18': 'LL_PHY_UPDATE_IND', '0x19': 'LL_MIN_USED_CHANNELS_IND', '0x1c': 'LL_PERIODIC_SYNC_IND', '0x1d': 'LL_CLOCK_ACCURACY_REQ', '0x1e': 'LL_CLOCK_ACCURACY_RSP', '0x1f': 'LL_CIS_REQ', '0x20': 'LL_CIS_RSP', '0x21': 'LL_CIS_IND', '0x22': 'LL_CIS_TERMINATE_IND', '0x23': 'LL_POWER_CONTROL_REQ', '0x24': 'LL_POWER_CONTROL_RSP', '0x25': 'LL_POWER_CHANGE_IND', '0x26': 'LL_SUBRATE_REQ', '0x27': 'LL_SUBRATE_IND', '0x28': 'LL_CHANNEL_REPORTING_IND', '0x29': 'LL_CHANNEL_STATUS_IND'}


dict_Interrupt_type = {'Interrupt_type': '', '0x00': 'TIM0_delay', '0x01': 'TIM1', '0x02': 'TIM2_delay', '0x03': 'TIM3', '0x04': 'SYNC', '0x05': 'PKA  ', '0x06': 'HDR        ', '0x07': 'PKD          ', '0x08': 'NO_PKT         ', '0x09': 'AES_COMPLETE ', '0x0a': 'AUX', '0x0b': 'RX_START'}


dict_Inquiry_fsm = {'Inquiry_fsm': '', '0x00': 'INQ_ST_START', '0x01': 'INQ_ST_END', '0x02': 'INQ_ST_NOT_ACTIVE', '0x03': 'INQ_ST_INQUIRY_TX_RX', '0x04': 'INQ_ST_EXTENDED_INQUIRY_RESPONSE', '0x05': 'INQ_ST_SUSPEND', '0x06': 'INQ_ST_RESUME'}


dict_Inquiry_scan_fsm = {'Inquiry_scan_fsm': '', '0x00': 'INQSCN_START', '0x01': 'INQSCN_END', '0x02': 'INQSCN_NOT_ACTIVE', '0x03': 'INQSCN_INQUIRY_SCAN', '0x04': 'INQSCN_INQUIRY_RAND_WAIT', '0x05': 'INQSCN_INQUIRY_RESPONSE', '0x06': 'INQSCN_INQUIRY_SCAN_RESUME', '': '', '0x07': 'INQSCN_INQUIRY_AML4_RESPONSE_COMPLETE', '0x08': 'INQSCN_INQUIRY_SCAN_2ND_TRAIN', '0x09': 'INQSCN_INQUIRY_GENERATE_EIR_PACKET'}


dict_Page_fsm = {'Page_fsm': '', '0x00': 'PAGE_START', '0x01': 'PAGE_END', '0x02': 'PAGE_NOT_ACTIVE', '0x03': 'PAGING_TX', '0x04': 'PAGING_RX', '0x05': 'MASTER_PAGE_RESP_TX', '0x06': 'MASTER_PAGE_RESP_RX', '0x07': 'MASTER_PAGE_RESP_LOOK_AHEAD_RX', '0x08': 'POLL_RESP_TX', '0x09': 'POLL_RESP_RX', '0x0a': 'POLL_RESP_LOOK_AHEAD_RX', '0x0b': 'PAGE_CONNECTED_TO_SLAVE', '0x0c': 'PAGING_LOOK_AHEAD_RX', '0x0d': 'PAGE_SUSPEND', '0x0e': 'PAGE_RESUME'}


dict_Page_scan_fsm = {'Page_scan_fsm': '', '0x00': 'PAGESCAN_START,', '0x01': 'PAGESCAN_END,', '0x02': 'PAGESCAN_NOT_ACTIVE,', '0x03': 'PAGESCAN_RESUME_PAGE_SCANNING,', '0x04': 'PAGESCAN_PAGE_SCAN,', '0x05': 'PAGESCAN_SLAVE_PAGE_RESP,', '0x06': 'PAGESCAN_POLL_RESP_RX,', '0x07': 'PAGESCAN_CONNECTED_TO_MASTER,', '0x08': 'PAGESCAN_END_AT_NEXT_TX_START,', '0x09': 'PAGESCAN_PAGESCAN_2ND_TRAIN'}


dict_LE_fsm = {'LE_fsm': '', '0x01': 'STANDBY_STATE', '0x02': 'ADVERTISING_STATE', '0x03': 'SCANNING_STATE', '0x04': 'INITIATING_STATE', '0x05': 'CONNECTION_STATE', '0x06': 'TEST_STATE', '0x07': 'LE_W4_MASTER_TIM0_OR_TIM2'}


dict_LE_adv_sub_fsm = {'LE_adv_sub_fsm': '', '0x00': 'SUBSTATE_IDLE   ', '0x01': 'W4_T2_PRE_ADV_TX', '0x02': 'W4_ADV_TX       ', '0x03': 'W4_ADV_RX       ', '0x04': 'W4_SCAN_RESP_TX ', '0x05': 'W4_N_x_T2       ', '0x06': 'W4_N_x_T0       ', '0x07': 'W4_T0_PRE_ADV_TX'}


dict_LE_scan_sub_fsm = {'LE_scan_sub_fsm': '', '0x10': 'W4_T2_PRE_SCAN       ', '0x20': 'W4_SCAN_RX           ', '0x30': 'W4_SCAN_TX           ', '0x40': 'W4_SCAN_RESP_RX      ', '0x50': 'W4_SCAN_RESUME       ', '0x60': 'W4_SCAN_PKD          ', '0x70': 'W4_SCAN_RESP_PKD     ', '0x80': 'W4_SCAN_DUMMY_TX     ', '0x90': 'W4_DUMMY_SCAN_RESP_TX ', '0xa0': 'W4_RESUME_SCAN       ', '0xb0': 'W4_RESUME_SCAN_NEXT_TIM ', '0xc0': 'W4_RESUME_FROM_CLASSIC ', '0xd0': 'W4_AUX_CONNECT_RESP_RX ', '0xe0': 'W4_AUX_CONNECT_RESP_PKD '}


dict_LE_connection_sub_fsm = {'LE_connection_sub_fsm': '', '0x01': 'W4_T2_MASTER_CONN_FIRST_TX     ', '0x02': 'W4_MASTER_CONN_FIRST_TX        ', '0x03': 'W4_MASTER_CONN_RX              ', '0x04': 'W4_MASTER_CONN_TX              ', '0x05': 'W4_T0_PRE_MASTER_FIRST_CONN_TX ', '0x10': 'W4_T0_PRE_SLAVE_CONN_FIRST_RX  ', '0x11': 'W4_T2_SLAVE_CONN_FIRST_RX      ', '0x12': 'W4_SLAVE_CONN_FIRST_RX         ', '0x13': 'W4_SLAVE_CONN_TX               ', '0x14': 'W4_SLAVE_CONN_RX               ', '0x15': 'W4_T1_SLAVE_CONN_FIRST_FULL_RX ', '0x16': 'W4_T2_SLAVE_CONN_FIRST_FULL_RX ', '0x17': 'W4_T0_PRE_SLAVE_CE             ', '0x18': 'W4_T2_PRE_SLAVE_CE             '}


dict_LE_adv_pdu = {'LE_adv_pdu': '', '0x00': 'ADV_IND', '0x01': 'ADV_DIRECT_IND', '0x02': 'ADV_NONCONN_IND', '0x03': 'SCAN_REQ', '0x04': 'SCAN_RSP', '0x05': 'CONNECT_REQ', '0x06': 'ADV_SCAN_IND', '0x07': 'ADV_EXT_IND', '0x17': 'AUX_ADV_IND', '0x27': 'AUX_SCAN_RSP', '0x37': 'AUX_SYNC_IND', '0x47': 'AUX_CHAIN_IND', '0x57': 'SYNC_CHAIN_IND', '0x67': 'SCAN_RSP_CHAIN_IND', '0x13': 'AUX_SCAN_REQ', '0x15': 'AUX_CONNECT_REQ', '0x08': 'AUX_CONNECT_RSP'}


dict_Sleep_sub_fsm = {'sleep_sub_fsm': '', '0x00': 'SLEEP_ST_INACTIVE', '0x01': 'SLEEP_ST_START', '0x02': 'SLEEP_ST_WAIT_RADIO_TO_SLEEP', '0x03': 'SLEEP_ST_WAIT_BASEBAND_TO_SLEEP', '0x04': 'SLEEP_ST_SLEEPING', '0x05': 'SLEEP_ST_WAKEN_RADIO', '0x06': 'SLEEP_ST_WAKEN_BASEBAND', '0x07': 'SLEEP_ST_REALIGN_FRAME_INTERRUPTS', '0x08': 'SLEEP_ST_REALIGN_FRAME_INTERRUPTS_2', '0x09': 'SLEEP_ST_END', '0x0a': 'SLEEP_ST_SENTINEL'}


dict_Packet_type = {'Packet_type': '', '0x00': 'NULLpkt', '0x01': 'POLLpkt', '0x02': 'FHSpkt', '0x03': 'DM1', '0x04': 'DH1', '0x05': 'HV1', '0x06': 'HV2', '0x07': 'HV3', '0x08': 'DV', '0x09': 'AUX1', '0x0a': 'DM3', '0x0b': 'DH3', '0x0c': 'EV4', '0x0d': 'EV5', '0x0e': 'DM5', '0x0f': 'DH5', '0x10': 'IDpkt', '0x11': 'INVALIDpkt', '0x14': '2DH1', '0x16': '2EV3', '0x15': 'EV3', '0x17': '3EV3', '0x18': '3DH1', '0x19': 'AUX1', '0x1a': '2DH3', '0x1b': '3DH3', '0x1c': '2EV5', '0x1d': '3EV5', '0x1e': '2DH5', '0x1f': '3DH5', '0x20': 'MAX_PKT'}


dict_TXRXstatus = {'TXRXstatus': '', '0x00': 'TX_READY', '0x01': 'RX_READY', '0x02': 'TX_OK', '0x03': 'TX_NONE', '0x04': 'RX_OK', '0x05': 'RX_NONE', '0x06': 'RX_DUPLICATE', '0x07': 'RX_NO_PACKET', '0x08': 'RX_RESTRICTED_PACKET', '0x09': 'RX_AMADDR_ERROR', '0x0a': 'HEC_ERROR', '0x0b': 'CRC_ERROR', '0x0c': 'TX_2_IDS_IN_SLOT', '0x0d': 'TX_UNEXPECTED_ERROR', '0x0e': 'RX_UNEXPECTED_ERROR', '0x0f': 'RX_BROADCAST_PACKET', '0x10': 'RX_BROADCAST_DUPLICATE', '0x11': 'RX_NORMAL_HEADER', '0x12': 'RX_BROADCAST_HEADER', '0x13': 'RX_MISSED_HEADER', '0x14': 'RX_NORMAL_HEADER_PRIMARY_LT_ADDR', '0x15': 'RX_NORMAL_HEADER_SECONDARY_LT_ADDR', '0x16': 'MIC_ERROR', '0x17': 'MIC_OK'}


dict_error_code_msg = {'error_code': '', '0x00': 'NO_ERROR', '0x01': 'ILLEGAL_COMMAND', '0x02': 'NO_CONNECTION', '0x03': 'HARDWARE_FAILURE', '0x04': 'PAGE_TIMEOUT', '0x05': 'AUTHENTICATION_FAILURE', '0x06': 'PIN_MISSING', '0x07': 'MEMORY_FULL', '0x08': 'CONNECTION_TIMEOUT', '0x09': 'MAX_NUM_CONNECTIONS', '0x0a': 'MAX_NUM_SCO', '0x0b': 'ACL_ALREADY_EXISTS', '0x0c': 'COMMAND_DISALLOWED', '0x0d': 'HOST_REJECT_LIMITED_RESOURCES', '0x0e': 'HOST_REJECT_SECURITY', '0x0f': 'HOST_REJECT_PERSONAL_DEVICE', '0x10': 'CONNECTION_ACCEPT_TIMEOUT', '0x11': 'UNSUPPORTED_FEATURE', '0x12': 'INVALID_HCI_PARAMETERS', '0x13': 'REMOTE_USER_TERMINATED_CONNECTION', '0x14': 'REMOTE_RESOURCES_TERMINATED_CONNECTION', '0x15': 'REMOTE_POWER_TERMINATED_CONNECTION', '0x16': 'LOCAL_TERMINATED_CONNECTION', '0x17': 'REPEATED_ATTEMPTS', '0x18': 'PAIRING_NOT_ALLOWED', '0x19': 'UNKNOWN_LMP_PDU', '0x1a': 'UNSUPPORTED_REMOTE_FEATURE', '0x1b': 'SCO_OFFSET_REJECTED', '0x1c': 'SCO_INTERVAL_REJECTED', '0x1d': 'SCO_AIR_MODE_REJECTED', '0x1e': 'INVALID_LMP_PARAMETERS', '0x1f': 'UNSPECIFIED_ERROR', '0x20': 'UNSUPPORTED_PARAMETER_VALUE', '0x21': 'ROLE_CHANGE_NOT_ALLOWED', '0x22': 'LMP_RESPONSE_TIMEOUT', '0x23': 'LMP_ERROR_TRANSACTION_COLLISION', '0x24': 'LMP_PDU_NOT_ALLOWED', '0x25': 'ENCRYPTION_MODE_NOT_ACCEPTABLE', '0x26': 'UNIT_KEY_USED', '0x27': 'QOS_NOT_SUPPORTED', '0x28': 'INSTANT_PASSED', '0x29': 'PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED', '0x2a': 'EC_DIFFERENT_TRANSACTION_COLLISION', '0x2b': 'EC_INSUFFICIENT_RESOURCES_FOR_SCATTER_MODE_REQUEST', '0x2c': 'EC_QOS_UNACCEPTABLE_PARAMETER', '0x2d': 'EC_QOS_REJECTED', '0x2e': 'EC_CHANNEL_CLASSIFICATION_NOT_SUPPORTED', '0x2f': 'EC_INSUFFICIENT_SECURITY', '0x30': 'EC_PARAMETER_OUT_OF_MANDATORY_RANGE', '0x31': 'EC_SCATTER_MODE_NO_LONGER_REQUIRED', '0x32': 'EC_ROLE_SWITCH_PENDING', '0x33': 'EC_SCATTER_MODE_PARAMETER_CHANGE_PENDING', '0x34': 'EC_RESERVED_SLOT_VIOLATION', '0x35': 'EC_ROLE_SWITCH_FAILED', '0x36': 'EC_EXTENDED_INQUIRY_RESPONSE_TOO_LARGE', '0x37': 'EC_SSP_NOT_SUPPORTED_BY_HOST', '0x38': 'EC_HOST_BUSY_PAIRING', '0x39': 'EC_CONNECTION_REJECTED_DUE_TO_NO_SUITABLE_CHANNEL_FOUND', '0x3a': 'EC_CONTROLLER_BUSY', '0x3b': 'EC_UNACCEPTABLE_CONNECTION_INTERVAL', '0x3c': 'EC_DIRECTED_ADVERTISING_TIMEOUT', '0x3d': 'EC_CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE','0x54': 'EFUSE_ADDR_NOT_SET', '0x57': 'EC_CONNECTION_FAILED_TO_BE_ESTABLISHED', '0x3e': 'EC_MAC_CONNECTION_FAILED'}


dict_ack_nak = {'ACK/NAK': '', '0x00': 'nak', '0x01': 'ack'}


dict_seqn_msg = {'seqn_msg': '', '0x00': '0x0', '0x01': '0x1'}


dict_LE_ce_msg = {'LE_connection_event_msg': '', '0x00': 'expired_time_ce', '0x01': 'connInterval', '0x02': 'current_clk', '0x03': 'next_ce_time', '0x04': 'miss_ce_times', '0x05': 'miss_ce, update_next_ce_time'}


dict_trig_msg = {'trig_msg': '', '0x00': 'trig_data', '0x01': 'trig_event'}

dict_role_log = {'role_log': '', '0x00': 'master', '0x01': 'slave'}

dict_debug_log_msg = {}

dict_pc_debug_log_msg = {}

dict_sjr_debug_log_msg = {}

dict_xyz_debug_log_msg = {}

dict_bei_debug_log_msg = {}

dict_init_debug_log_msg = {}

dict_isoal_debug_log_msg = {}
dict_big_debug_log_msg = {}
dict_cig_debug_log_msg = {'0xc1': 'cig_is_reset'}
dict_le_audio_debug_log_msg = {}
dict_pawr_debug_log_msg = {}
dict_le_conn_debug_log_msg = {}
dict_le_adv_debug_log_msg = {}
dict_le_scan_debug_log_msg = {}
dict_le_ll_debug_log_msg = {}
dict_le_comm_debug_log_msg = {}
dict_event_list_debug_log_msg = {}
dict_host_if_debug_log_msg = {}


dict_bt_wifi_coex = {'[coex] bt_wifi_coex': '', '0x00': '[coex] dis_bt_thread', '0x01': '[coex] rst_bt_thread', '0x02': '[coex] close_bt', '0x03': '[coex] cur_clk', '0x04': '[coex] wf_st_close', '0x05': '[coex] coex_irq_type', '0x06': '[coex] wf_st_close', '0x07': '[coex] wf_th_end_bt_close', '0x08': '[coex] wf_th_end,cur_clk', '0x09': '[coex] wf,bt,15.4 time slice', '0x0a': '[coex] bt_act_timer', '0x0b': '[coex] bt_15p4_channel_overlap', '0x0c': '[coex] wf,bt,15.4 pri', '0x0d': '[coex] bt_avoid_15p4_channel', '0x0e': '[coex] wf_th_end_invalid', '0x0f': '[coex] delt2_last_wf_end', '0x10': '[coex] wf_act_timer', '0x11': '[coex] bt_avoid_wifi_channel', '0x12': 'wf,bt grant', '0x13': '[coex] wf_st_open', '0x14': '[coex] wf_st_close_2_bt_only', '0x15': '[coex] bt_open', '0x16': '[coex] bt_close', '0x17': 'aml_coex_arbitration begin', '0x18': 'aml_coex_arbitration end', '0x19': 'aml_coex_core begin', '0x1a': 'aml_coex_core end', '0x1b': 'g_bt_min_grant', '0x1c': 'enable_rx', '0x1d': 'enable_rx_end', '0x1e': 'sleep_procedure_start', '0x1f': 'sleep_procedure_end', '0x20': 'BT_WAKE_START', '0x21': 'BT_WAKE_END', '0x22': '[coex] bt_th_end', '0x23': '[coex] req_id', '0x24': '[coex] must_switch_to_bt', '0x25': '[coex] stop_bt_th', '0x26': '[coex] bt_send_req', '0x27': '[coex] bt_req_info', '0x28': '[coex] bt_anchor_info', '0x29': '[coex] must_sw2_le' , '0x2a': '[coex] 15p4_act_timer', '0x2b': '[coex] coex_mode'}

dict_DBG_COEX_ARB_LOG = {'DBG_COEX_ARB_LOG': '', '0x00': '[coex arb] bt request:', '0x01': '[coex arb] 15p4 request:', '0x02': '[coex arb] wifi request:', '0x03': '[coex arb] 15p4 response:', '0x04': '[coex arb] bt priority:', '0x05': '[coex arb] 15p4 priority:', '0x06': '[coex arb] wifi priority:', '0x07': '[coex arb] bt active time:', '0x08': '[coex arb] 15p4 active time:', '0x09': '[coex arb] wifi active time:', '0x0a': '[coex arb] switch to bt:', '0x0b': '[coex arb] switch to 15p4:', '0x0c': '[coex arb] switch to wifi:', '0x0d': '[coex arb] 15p4 timeslice:', '0x0e': '[coex arb] wifi timeslice:', '0x20': '[coex arb] bt switch flag:', '0x99': '[coex arb] dbg:' }

dict_DBG_COEX_BT_LOG = {'DBG_COEX_BT_LOG': '', '0x00': '[coex bt] thread para:', '0x0a': '[coex bt] dbg:'}

dict_DBG_COEX_15P4_LOG = {'DBG_COEX_15P4_LOG': '', '0x00': '[coex 15p4] thread para:'}
dict_DBG_COEX_WIFI_LOG = {'DBG_COEX_WIFI_LOG': '', '0x00': '[coex wifi] thread para:'}
