# This is yaml for ASUS router xpath info

asus:
  address:
    '5400': http://192.168.1.1/
    86u: http://192.168.50.1/
    88u: http://192.168.50.1/
    '6700': http://192.168.8.1/
  account: admin
  passwd: 12345678
  username_element: login_username
  password_element: login_passwd
  signin_element:
    asus_5400: //*[@id="button"]
    asus_86u: //*[@id="login_filed"]/div[8]
    asus_88u: //*[@id="login_filed"]/div[9]
    asus_6700: //*[@id="login_filed"]/div[8]
  signin_done_element: helpname

  country_code_element:
    asus_5400:
    asus_86u:
    asus_88u: //*[@id="region_div"]/select/option[{}]
    asus_6700:
  smart_connect_element:
    asus_5400:
    asus_86u:
    asus_88u: iphone_switch
    asus_6700:

  band_element: //*[@id="wl_unit_field"]/td/select
  wireless_mode_element:
    asus_5400: //*[@id="WLgeneral"]/tbody/tr[6]/td/select
    asus_86u: //*[@id="WLgeneral"]/tbody/tr[6]/td/select
    asus_88u: //*[@id="WLgeneral"]/tbody/tr[6]/td/select
#    //*[@id="WLgeneral"]/tbody/tr[6]/td/select/option[1]
    asus_6700: //*[@id="WLgeneral"]/tbody/tr[6]/td/select/option[{}]

  wireless_ax_element:
    asus_5400: //*[@id="button"]
    asus_86u: //*[@id="he_mode_field"]/td/div/select/option[{}]
    asus_88u: //*[@id="he_mode_field"]/td/div/select/option[{}]
    asus_6700: //*[@id="login_filed"]/div[8]
  ssid_element: wl_ssid

#  //*[@id="WLgeneral"]/tbody/tr[9]/td/select/option[1]
  channel_element:
    asus_5400: //*[@id="WLgeneral"]/tbody/tr[11]/td/select
    asus_86u: //*[@id="WLgeneral"]/tbody/tr[11]/td/select
    asus_88u: //*[@id="WLgeneral"]/tbody/tr[11]/td/select
    asus_6700: //*[@id="WLgeneral"]/tbody/tr[9]/td/select
  bandwidth_element: //*[@id="wl_bw_field"]/td/select

  authentication_method_element:
    asus_5400: //*[@id="WLgeneral"]/tbody/tr[13]/td/div[1]/select
    asus_86u: //*[@id="WLgeneral"]/tbody/tr[13]/td/div[1]/select
    asus_88u: //*[@id="WLgeneral"]/tbody/tr[13]/td/div[1]/select
    asus_6700: //*[@id="WLgeneral"]/tbody/tr[11]/td/select

  wep_encrypt_regu_element:
    asus_5400: //*[@id="WLgeneral"]/tbody/tr[16]/td/select/option[{}]
    asus_86u: //*[@id="WLgeneral"]/tbody/tr[16]/td/select
    asus_88u: //*[@id="WLgeneral"]/tbody/tr[16]/td/select
    asus_6700: //*[@id="WLgeneral"]/tbody/tr[14]/td/select/option[{}]

  wpa_encrypt_element: //*[@id="WLgeneral"]/tbody/tr[14]/td/select
  passwd_index_element:
    asus_5400: //*[@id="WLgeneral"]/tbody/tr[17]/td/select
    asus_86u: //*[@id="WLgeneral"]/tbody/tr[17]/td/select
    asus_88u: //*[@id="WLgeneral"]/tbody/tr[17]/td/select
    asus_6700: //*[@id="WLgeneral"]/tbody/tr[15]/td/select

  wep_passwd_element: wl_key1
  wpa_passwd_element:
    asus_5400: //*[@id="wpa_psk_key_field"]/td/div/div[1]/input
    asus_86u: //*[@id="wpa_psk_key_field"]/td/div/div[1]/input
    asus_88u: //*[@id="wpa_psk_key_field"]/td/div/div[1]/input
    asus_6700: //*[@id="WLgeneral"]/tbody/tr[13]/td/input

  protect_frame_element:
    asus_5400: //*[@id="WLgeneral"]/tbody/tr[26]/td/select
    asus_86u: //*[@id="WLgeneral"]/tbody/tr[26]/td/select
    asus_88u: //*[@id="WLgeneral"]/tbody/tr[26]/td/select
    asus_6700: //*[@id="WLgeneral"]/tbody/tr[24]/td/select
  apply_element: applyButton
  setting_load_element: //*[@id="loadingBlock"]/tbody/tr/td[2]

  wait_reboot_element:
    asus_5400: /html/body/form/div/div/div[1]/div[1]
    asus_86u: /html/body/form/div/div/div[1]/div[2]
    asus_88u: /html/body/form/div/div/div[2]