concomitant_dut: '{''device_number'': ''aq2228019431943b23a0d'', ''status'': False}'
connect_type:
  adb:
    device: coco_aaaaaa
  telnet:
    ip: 192.168.1.102
  type: telnet
corner_angle:
  ip_address: 192.168.5.11
  step:
  - 0
  - 320
fpga: w2_sdio
power_relay: '{''192.168.200.6'': ''7''}'
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.50.19
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.50.10
  model: XIN-YI
  step:
  - 0
  - 19
router:
  name: asusax5400
rvr:
  iperf:
    path: ''
    version: iperf3
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  pair: '5'
  repeat: '0'
  tool: iperf
serial_port:
  baud: '961200'
  port: COM5
  status: false
text_case: C:/Users/SH171300-1522/PycharmProjects/wifi_test/src/test/performance/test_wifi_rvr.py
