# This is yaml for DUT info
connect_type:
  type: telnet
  adb:
    device: 'ap2228019621984103f16'
  telnet:
    ip: '192.168.50.12'
    #    market 区域 默认填写 sandia  支持列表：sandia,sandia_latam,sandia_hkc,sandia_dvb
    wildcard: bayside

# Router model
router:
  # pls write down the router name .It should be asusac88u or asusax86u
  name: asusax88u

# test env control , should be rf , corner or both
env_control: rf

# Attenuation information. It should be RC4DAT-8G-95 or RADIORACK-4-220
rf_solution:
  model: RADIORACK-4-220
  RC4DAT-8G-95:
    idVendor: 0x20ce
    idProduct: 0x0023
    ip_address: 192.168.50.10
  RADIORACK-4-220:
    ip_address: 192.168.50.19
  # reduction step for rf signal, can be configured according to test requirements
  step: [ 0,2 ]

# Turntable information
corner_angle:
  # angle step for corner, can be configured according to test requirements
  ip_address: 192.168.50.18
  step: [ 0, 360 ]

rvr:
  tool: iperf
  iperf:
    # should be iperf or iperf3
    version: iperf
    # dut iperf path
    path:
  ixchariot:
  pair: 10
  repeat: 0

env_command: [ "pwd" ]
#env_command: [ "iwpriv wlan0 set_rate_ofdm 9","iwpriv wlan0 set_rate_ofdm 8","iwpriv wlan0 set_rate_ofdm 3" ]
#test_wifi:
#  ssid: i-test
#  passwd: "@12345678"

# Number of channels played
pair_num:
  ax:
    '2': { 'tx': [ 15,10,6,4,2 ],'rx': [ 15,10,6,4,2 ] }
    '5': { 'tx': [ 35,35,15,6,4,2 ],'rx': [ 35,35,15,6,4,2 ] }
  ac:
    '5': { 'tx': [ 15,10,6,4,2 ],'rx': [ 15,10,6,4,2 ] }
  'auto':
    '2': { 'tx': [ 15,10,6,4,2 ],'rx': [ 15,10,6,4,2 ] }
    '5': { 'tx': [ 15,15,15,6,4,2 ],'rx': [ 15,15,15,6,4,2 ] }
  n:
    '2': { 'tx': [ 15,10,6,4,2 ],'rx': [ 15,10,6,4,2 ] }
    '5': { 'tx': [ 15,15,10,6,4,2 ],'rx': [ 15,15,10,6,4,2 ] }

#
concomitant_dut:
  status: False
  device_number: aq2228019431943b23a0d


mysql:
  host: 192.168.50.169
  user: visitor
  passwd: 123456
  database: wifi_test