Turntable:
  Turntable: RS232Board5
  IP address: 192.168.5.156
  Step: 0,360:45
  Static dB: ''
  Target RSSI: ''
rf_solution:
  HJ-RADIORACK-4-220:
    ip_address: 192.168.1.230
  SWD-RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.200.102
  Vaunix-LDA-908V-8:
    ip_address: 192.168.10.43
    channels: 1,2,3,8
  model: SY-RS232Board5
  step:
    Dual: 0,75:3
    2.4G: 0,75:3
    5G: 0,75:3
text_case: test/performance/test_wifi_rvo.py
debug:
  database_mode: true
  skip_router: false
  skip_corner_rf: false
  skip_connect: false
csv_path: ''
mode: Wi-Fi BLE CLASSIC
bt:
  ble_alias: Remote
  classic_alias: JBL
lab:
  name: SH-RVR-2
function:
  customer: ''
  project_type: ''
  project: ''
  odm: ''
  soc: ''
  wifi_module: ''
  interface: ''
atte:
  model: SY-RS232Board5
lab_enviroment:
  coex_mode: WiFi+BLE
  ap_region: CN
