corner_angle:
  ip_address: 192.168.5.156
  step:
  - 0
  - 90
  static_db: 10,20
  target_rssi: 35,45
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.50.19
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.5.75
  LDA-908V-8:
    ip_address: 192.168.5.200
    channels: '1'
  model: RC4DAT-8G-95
  step: '0,75:3'
rvr:
  iperf:
    path: ''
    server_cmd: iperf -s -i 1
    client_cmd: iperf -c {ip} -i 1 -t 10 -P 1
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  repeat: '0'
  throughput_threshold: '5'
  tool: iperf
router:
  name: asusax88u
  address: 192.168.5.1
text_case: test/performance/test_wifi_rvr.py
software_info:
  software_version: ''
  driver_version: ''
hardware_info:
  hardware_version: ''
android_system:
  version: ''
  kernel_version: ''
connect_type:
  adb:
    device: coco5c6788c23f1804
  telnet:
    ip: 192.168.5.12
  third_party:
    enabled: false
    wait_seconds: 45
  type: telnet
fpga: W1U_PCIE
serial_port:
  baud: '961200'
  port: COM5
  status: false
