# This is yaml for DUT info
connect_type:
  type: adb
  adb:
    device: 'twilight9de10187801e1c'
  telnet:
    ip: '192.168.50.110'
    #    market area  sandia  list:sandia,sandia_latam,sandia_hkc,sandia_dvb
    wildcard: sandia_dvb

# model such as w1 w1u w2 w2l
fpga: w2_sdio

host_os:
  user: amlogic
  password: '123456'

serial_port:
  port: 'COM5'
  baud: 961200

# Router model
router:
  # pls write down the router name .
  # It should be asusax86u,asusax88u,asusax5400,asusax6700,xiaomiredax6000,xiaomiax3000
  name: xiaomiredax6000

power_relay: {
  '192.168.200.3': '12345678',
  '192.168.200.4': '12345678'
}

# test env control , should be rf , corner or both
env_control: rf

# Attenuation information. It should be RC4DAT-8G-95 or RADIORACK-4-220
rf_solution:
  model: RADIORACK-4-220
  RC4DAT-8G-95:
    idVendor: 0x20ce
    idProduct: 0x0023
    ip_address: 192.168.50.10
  RADIORACK-4-220:
    ip_address: 192.168.50.19
  # reduction step for rf signal, can be configured according to test requirements
  step: [ 0,50 ]

# Turntable information
corner_angle:
  # angle step for corner, can be configured according to test requirements
  ip_address: 192.168.50.18
  step: [ 0, 360 ]

rvr:
  tool: iperf
  iperf:
    # should be iperf or iperf3
    version: iperf
    # dut iperf path
    path:
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  pair: 2
  # re-test count , type 0 means don't repeat test once ,type 1 means repeat one time,totally get two test result totally
  repeat: 0


# Number of channels played
pair_num:
  ax:
    '2': { 'tx': [ 15,10,6,4,2 ],'rx': [ 15,10,6,4,2 ] }
    '5': { 'tx': [ 35,35,15,6,4,2 ],'rx': [ 35,35,15,6,4,2 ] }
  ac:
    '5': { 'tx': [ 15,10,6,4,2 ],'rx': [ 15,10,6,4,2 ] }
  'auto':
    '2': { 'tx': [ 15,10,6,4,2 ],'rx': [ 15,10,6,4,2 ] }
    '5': { 'tx': [ 15,15,15,6,4,2 ],'rx': [ 15,15,15,6,4,2 ] }
  n:
    '2': { 'tx': [ 15,10,6,4,2 ],'rx': [ 15,10,6,4,2 ] }
    '5': { 'tx': [ 15,15,10,6,4,2 ],'rx': [ 15,15,10,6,4,2 ] }

#
concomitant_dut:
  status: False
  device_number: aq2228019431943b23a0d


mysql:
  host: 192.168.50.169
  user: visitor
  passwd: 123456
  database: wifi_test