serial_port:
  baud: '115200'
  port: COM5 (Silicon Labs CP210x USB to UART Bridge (COM5))
  status: false
router:
  name: asusax88upro
  address: 192.168.50.1
  24g_ssid: 2.4G
  5g_ssid: 5G
rvr:
  tool: iperf
  iperf:
    path: ''
    server_cmd: iperf -s -i 1
    client_cmd: iperf -c {ip} -i 1  -t 5 -P 5
  ixchariot:
    path: ''
  repeat: '0'
  throughput_threshold: ''
dut:
  type: Android
  Android:
    device: No devices
  Linux:
    ip: 10.28.38.10
    wildcard: ''
  third_party:
    enabled: false
    wait_seconds: 0
  name: asusax88u
  address: 192.168.8.1
  24g_ssid: Openwrt-AT-24G
  5g_ssid: Openwrt-AT-5G
  mac_address: 1c:a4:10:6e:48:c1
