software_info:
  software_version: ''
  driver_version: ''
hardware_info:
  hardware_version: ''
system:
  version: Android 15
  kernel_version: Kernel 6.1
project:
  customer: XIAOMI
  product_line: TV
  project: Vodka424
  odm: '-'
  main_chip: T966D5
  wifi_module: W265U1
  interface: USB
  mass_production_status: EVT
  dut_sn: ''
serial_port:
  baud: '115200'
  port: ''
  status: false
router:
  name: xiaomibe7000
  address: 192.168.31.1
  24g_ssid: 2.4G
  5g_ssid: 5G
rvr:
  tool: iperf
  iperf:
    path: ''
    server_cmd: ''
    client_cmd: ''
  ixchariot:
    path: ''
  repeat: ''
  throughput_threshold: ''
dut:
  type: Android
  Android:
    device: No devices
  Linux:
    ip: 10.28.38.10
    wildcard: ''
  third_party:
    enabled: false
    wait_seconds: 0
  name: asusax88u
  address: 192.168.8.1
  24g_ssid: Openwrt-AT-24G
  5g_ssid: Openwrt-AT-5G
  mac_address: ''
