connect_type:
  adb:
    device: coco5c6788c23f1804
  telnet:
    ip: 192.168.1.102
  type: telnet
corner_angle:
  ip_address: 192.168.5.11
  step:
  - 0
  - 320
fpga: W2U_USB
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.50.19
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.5.75
  model: RC4DAT-8G-95
  step:
  - 65
  - 70
router:
  name: asusax88u
  address: 192.168.5.1
rvr:
  iperf:
    path: ''
    server_cmd: iperf -s -w 2m -i 1
    client_cmd: iperf -c {ip} -w 2m -i 1 -t 30 -P 1
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  repeat: '0'
  throughput_threshold: '5'
  tool: iperf
serial_port:
  baud: '961200'
  port: COM5
  status: false
text_case: test/performance/test_wifi_peak_throughput.py
csv_path: performance_test_csv/asus/rvr_wifi_setup_demo.csv
