panels:
  execution:
    layout: "grid"
    columns: 2
    sections:
      - id: lab
        label: ""
        position: 0
        fields:
          - key: lab.name
            widget: combo_box
            label: "Lab"

      - id: rf_solution
        label: "RF Attenuator"
        position: 1
        fields:
          - key: atte.model
            widget: read_only_text
            label: "Attenuator Model"
          - key: rf_solution.RC4DAT-8G-95.idVendor
            widget: line_edit
            #label: "RC4DAT-8G-95 idVendor"
            label: "Attenuator idVendor"
          - key: rf_solution.RC4DAT-8G-95.idProduct
            widget: line_edit
            #label: "RC4DAT-8G-95 idProduct"
            label: "Attenuator idProduct"
          - key: rf_solution.RC4DAT-8G-95.ip_address
            widget: line_edit
            #label: "RC4DAT-8G-95 IP"
            label: "Attenuator IP"
          - key: rf_solution.RADIORACK-4-220.ip_address
            widget: line_edit
            #label: "RADIORACK-4-220 IP"
            label: "Attenuator IP"
          - key: rf_solution.LDA-908V-8.ip_address
            widget: line_edit
            #label: "LDA-908V-8 IP"
            label: "Attenuator IP"
          - key: rf_solution.LDA-908V-8.channels
            widget: line_edit
            #label: "LDA-908V-8 Channels"
            label: "Attenuator Channels"
          - key: rf_solution.step
            widget: custom
            label: "Step"
          - key: rf_solution.model
            widget: line_edit
            label: "RF Model"


      - id: Turntable
        label: "Turntable"
        fields:
          - key: Turntable.model
            widget: combo_box
            label: "Turntable"
          - key: Turntable.ip_address
            widget: line_edit
            label: "IP address"
            placeholder: "192.168.x.x"
          - key: Turntable.step
            widget: line_edit
            label: "Step"
            placeholder: "0,360 or 0,75:3"
          - key: Turntable.static_db
            widget: line_edit
            label: "Static dB"
            placeholder: "Static attenuation (dB)"
          - key: Turntable.target_rssi
            widget: line_edit
            label: "Target RSSI"
            placeholder: "Target RSSI (dBm)"

      - id: text_case
        label: "Selected Test Case"
        position: 2
        fields:
          - key: text_case
            widget: read_only_text
            label: "Test case"

      - id: csv_path
        label: "Performance CSV"
        fields:
          - key: csv_path
            widget: combo_box
            label: "Select config csv file"

      - id: mode
        label: "Wi-Fi BT Coex"
        fields:
          - key: mode
            widget: combo_box
            label: "Coex Mode"
            choices: ["Wi-Fi Only", "Wi-Fi BLE", "Wi-Fi BLE CLASSIC"]
          - key: bt.ble_alias
            widget: line_edit
            label: "BLE alias"
            placeholder: ""
          - key: bt.classic_alias
            widget: line_edit
            label: "Classic alias"
            placeholder: "Classic device alias"

      - id: throughput
        label: "Data Generator"
        fields:
          - key: rvr.tool
            widget: combo_box
            label: "Data Tool"
            choices: ["iperf", "ixchariot"]
          - key: rvr.iperf.path
            widget: line_edit
            label: "iperf Path (DUT)"
          - key: rvr.iperf.server_cmd
            widget: line_edit
            label: "iperf Server Cmd"
          - key: rvr.iperf.client_cmd
            widget: line_edit
            label: "iperf Client Cmd"
          - key: rvr.ixchariot.path
            widget: line_edit
            label: "IxChariot Path"
          - key: rvr.repeat
            widget: line_edit
            label: "Repeat"
            placeholder: "0"
          - key: rvr.throughput_threshold
            widget: line_edit
            label: "Zero Point Threshold"
            placeholder: "0"

      - id: debug
        label: "Debug Options"
        fields:
          - key: debug.skip_router
            widget: checkbox
            label: "Skip router workflow"
          - key: debug.skip_connect
            widget: checkbox
            label: "Skip DUT Wi-Fi connect workflow"
          - key: debug.skip_corner_rf
            widget: checkbox
            label: "Skip corner && RF workflow"
